<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_akquickicons
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


/**
 * Akquickicons helper.
 */
class AkquickiconsHelperDb
{
	public static function getSelectList( $tables = array() , $all = true )
	{
		return AkquickiconsHelper::_('query.getSelectList', $tables , $all);
	}
	
	public static function mergeFilterFields( $filter_fields , $tables = array() )
	{
		return AkquickiconsHelper::_('query.mergeFilterFields', $filter_fields , $tables);
	}
	
}
