<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_akquickicons
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;


/**
 * Akquickicons helper.
 */
class AkquickiconsHelperInclude
{
	static $bootstrap ;
	static $bluestork ;
	
	/*
	 * function core
	 * @param 
	 */
	
	public static function core($js = true)
	{
		$doc = JFactory::getDocument();
		$app = JFactory::getApplication() ;
		
		$prefix = $app->isAdmin() ? '../' : '' ;
		
		JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/css/akquickicons-core.css');
		JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/css/akquickicons.css');
		
		if($js){
			JHtml::_('behavior.framework', true);
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/js/akquickicons-core.js', true);
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/js/akquickicons.js', true);
		}
	}
	
	
	/*
	 * function foundation
	 * @param 
	 */
	
	public static function foundation($appl = true, $js = true)
	{
		$doc = JFactory::getDocument();
		$app = JFactory::getApplication() ;
		
		$prefix = $app->isSite() ? 'administrator/' : '' ;
		
		JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/foundation/stylesheets/foundation.min.css');
		if($appl) JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/foundation/stylesheets/app.css');
		
		if($js){
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/foundation/javascripts/modernizr.foundation.js');
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/foundation/javascripts/foundation.min.js');
			if($appl) JHtml::_('script', $prefix.'components/com_akquickicons/includes/foundation/javascripts/app.js');
		}
	}
	
	/*
	 * function bootstrap
	 * @param 
	 */
	
	public static function bootstrap($responsive = false, $js = true)
	{	
		$doc = JFactory::getDocument();
		$app = JFactory::getApplication() ;
		
		$prefix = $app->isSite() ? 'administrator/' : '' ;
		$min	= JDEBUG ? '.min' : '' ;
		
		if(JVERSION < 3){
			JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/bootstrap/css/bootstrap'.$min.'.css');
		}else{
			JHtml::_('bootstrap.loadCss') ;
		}
		
		if($responsive && JVERSION < 3 ){
			JHtml::_('stylesheet', $prefix.'components/com_akquickicons/includes/bootstrap/css/bootstrap-responsive'.$min.'.css');
		}
		
		if( $js && JVERSION < 3 ){
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/bootstrap/js/jquery.js');
			JHtml::_('script', $prefix.'components/com_akquickicons/includes/bootstrap/js/bootstrap'.$min.'.js');
			
			if( JVERSION < 3 ) {
				$doc->addScriptDeclaration("jQuery.noConflict();") ;
			}
		}else{
			JHtml::_('jquery.framework', true ,JDEBUG) ;
			JHtml::_('bootstrap.framework', JDEBUG) ;
		}
		
		self::$bootstrap = true ;
	}
	
	
	/*
	 * function bluestork
	 * @param 
	 */
	
	public static function bluestork()
	{
		$doc = JFactory::getDocument();
		$app = JFactory::getApplication() ;
		
		$doc->addStylesheet('administrator/templates/bluestork/css/template.css');
		
		$prefix = $app->isSite() ? 'administrator/' : '' ;
		
		self::$bluestork = true ;
	}
	
	
	/*
	 * function fixBluestorkAndBootstrap
	 * @param 
	 */
	
	public static function fixBootstrapToJoomla()
	{
		JHtml::_('stylesheet', 'components/com_akquickicons/includes/css/fix-bootstrap-to-joomla.css');
		
		JHtml::_('behavior.framework', true);
		JHtml::_('script', 'components/com_akquickicons/includes/js/fix-bootstrap-to-joomla.js', true);
	}
	
	
	
}