<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_akquickicons
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc 	= JFactory::getDocument();
$app 	= JFactory::getApplication();
$lang 	= JFactory::getLanguage();



// Define
// ========================================================================
define('AKQUICKICONS_SITE' , JPATH_COMPONENT_SITE );
define('AKQUICKICONS_ADMIN', JPATH_COMPONENT_ADMINISTRATOR);
define('AKQUICKICONS_SELF' , JPATH_COMPONENT);

if(!defined('DS')){
	define('DS', DIRECTORY_SEPARATOR) ;
}


// Include global helper.
include_once JPath::clean( JPATH_COMPONENT_ADMINISTRATOR . '/class/proxy.class.php' ) ;
include_once JPath::clean( JPATH_COMPONENT_ADMINISTRATOR . "/helpers/akquickicons.php" ) ;
include_once JPath::clean( JPATH_COMPONENT_ADMINISTRATOR . "/includes/loader.php" ) ;
include_once JPath::clean( JPATH_ADMINISTRATOR . "/includes/toolbar.php" ) ;
AkquickiconsHelper::setPrefix('AkquickiconsHelper') ;
AkquickiconsHelper::addIncludePath(JPATH_COMPONENT_ADMINISTRATOR . '/helpers/core');
AkquickiconsHelper::addIncludePath(JPATH_COMPONENT_ADMINISTRATOR . '/helpers/custom');



// Include joomla api
// ========================================================================
jimport('joomla.application.component.controller');
jimport('joomla.application.component.controllerform');
jimport('joomla.application.component.controlleradmin');

jimport('joomla.application.component.view');

jimport('joomla.application.component.modeladmin');
jimport('joomla.application.component.modellist');
jimport('joomla.application.component.modelitem');

jimport('joomla.html.toolbar');

jimport('joomla.filesystem.folder');
jimport('joomla.filesystem.file');



// Include Component Custom class
// ========================================================================
akquickiconsLoader("admin://class/viewpanel.class" ) ;
akquickiconsLoader("admin://class/aktext.class" ) ;
akquickiconsLoader("admin://class/toolbar.class" ) ;
akquickiconsLoader("admin://class/fieldmodal.class" ) ;
akquickiconsLoader("admin://class/akhelper/akhelper.init" ) ;



// Include Helpers
// ========================================================================

if( $app->isSite() ){
	
	// Include Admin language as global language.
	$lang->load('', JPATH_ADMINISTRATOR);
	$lang->load('com_akquickicons', JPATH_COMPONENT_ADMINISTRATOR );
	
	// Include Joomla! admin css
	AkquickiconsHelper::_('include.core');
	
	// set Base to fix toolbar anchor bug
	$doc->setBase( JFactory::getURI()->toString() );
	
}else{
	
}


// Detect version
AkquickiconsHelper::_('version.detectVersion');

