<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_akquickicons
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$doc 	= JFactory::getDocument();
$app 	= JFactory::getApplication();
$lang 	= JFactory::getLanguage();



// Define
// ========================================================================
define('AKQUICKICONS_SITE' , JPATH_COMPONENT_SITE );
define('AKQUICKICONS_ADMIN', JPATH_COMPONENT_ADMINISTRATOR);
define('AKQUICKICONS_SELF' , JPATH_COMPONENT);



// Include Helpers
// ========================================================================

// Core init, it can use by module, plugin or other component.
include_once JPath::clean( JPATH_ADMINISTRATOR . "/components/com_akquickicons/includes/core.php" ) ;


// Some useful settings
if( $app->isSite() ){
	
	// Include Admin language as global language.
	$lang->load('', JPATH_ADMINISTRATOR);
	$lang->load('com_akquickicons', JPATH_COMPONENT_ADMINISTRATOR );
	AkquickiconsHelper::_('lang.loadAll', $lang->getTag());
	
	
	// Include Joomla! admin css
	AkquickiconsHelper::_('include.sortedStyle', 'includes/css');
	
	
	// set Base to fix toolbar anchor bug
	$doc->setBase( JFactory::getURI()->toString() );
	
}else{
	AkquickiconsHelper::_('lang.loadAll', $lang->getTag());
	AkquickiconsHelper::_('include.sortedStyle', 'includes/css');
}


// Detect version
AkquickiconsHelper::_('plugin.attachPlugins');

// Debug
define('AKDEBUG', AkquickiconsHelper::_('system.getConfig', 'system.debug')) ;

// Panel
AkquickiconsHelper::_('panel.setLegacy', true) ;
