<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

JHtml::_('behavior.tooltip');
JHtml::_('behavior.multiselect');
JHtml::_('formbehavior.chosen', 'select');

$user = JFactory::getUser();
$userId = $user->get('id');
$input = JFactory::getApplication()->input;

$data = $this->data;

$function = $input->get('function', 'jSelectArticle');
$listOrder = $data->state->get('list.ordering');
$listDirn = $data->state->get('list.direction');
$canOrder = $user->authorise('core.edit.state', 'com_flower');
$saveOrder = $listOrder == 'a.ordering';
$nested = $data->state->get('items.nested');
$show_root = $input->get('show_root');

$lang = JFactory::getLanguage();
$lang->load('com_plugins');
?>
<form action="<?php echo $uri = JFactory::getURI()->toString(); ?>" method="post" name="adminForm" id="adminForm">

	<div id="filter-bar" class="btn-toolbar">
		<!-- Search Input -->

		<div class="btn-group pull-left fltlft">
			<?php
			$field = $data->filter['search']->getField('field');
			echo $field->label . ' ';
			?>
		</div>

		<div class="btn-group pull-left fltlft">
			<?php
			if (!$data->state->get('search.fulltext'))
			{
				echo $field->input;
			}
			?>
		</div>

		<div class="btn-group pull-left fltlft">
			<?php
			$index = $data->filter['search']->getField('index');
			echo $index->input;
			?>
		</div>

		<!-- Search Button -->
		<?php if (JVERSION >= 3): ?>
			<div class="btn-group pull-left hidden-phone">
				<button class="btn tip hasTooltip" type="submit" title="<?php echo JText::_('JSEARCH_FILTER_SUBMIT'); ?>">
					<i class="icon-search"></i></button>
				<button class="btn tip hasTooltip" type="button" onclick="document.id('search_index').value='';this.form.submit();" title="<?php echo JText::_('JSEARCH_FILTER_CLEAR'); ?>">
					<i class="icon-remove"></i></button>
			</div>
		<?php else: ?>

			<button type="btn submit"><?php echo JText::_('JSEARCH_FILTER_SUBMIT'); ?></button>
			<button type="btn button" onclick="document.id('search_index').value='';this.form.submit();"><?php echo JText::_('JSEARCH_FILTER_CLEAR'); ?></button>

		<?php endif; ?>
	</div>

	<table class="adminlist table table-striped">
		<thead>
		<tr>

			<th class="title">
				<?php echo JHtml::_('grid.sort', 'JGLOBAL_TITLE', 'a.title', $listDirn, $listOrder); ?>
			</th>
			<th width="15%" class="center nowrap">
				<?php echo JHtml::_('grid.sort', 'JCATEGORY', 'a.catid', $listDirn, $listOrder); ?>
			</th>
			<th width="25%" class="center nowrap">
				<?php echo JHtml::_('grid.sort', 'JDATE', 'a.created', $listDirn, $listOrder); ?>
			</th>
			<th width="1%" class="center nowrap">
				<?php echo JHtml::_('grid.sort', 'JGRID_HEADING_ID', 'a.id', $listDirn, $listOrder); ?>
			</th>

		</tr>
		</thead>
		<tfoot>
		<tr>
			<td colspan="10">
				<?php //echo $data->pagination->getListFooter(); ?>
			</td>
		</tr>
		</tfoot>
		<tbody>
		<?php foreach ($data->items as $i => $item) :

			$item = new JObject($item);

			$ordering   = ($listOrder == 'a.ordering');
			$canCreate  = $user->authorise('core.create', 'com_flower');
			$canEdit    = $user->authorise('core.edit', 'com_flower.sakura.' . $item->id);
			$canCheckin = $user->authorise('core.manage', 'com_flower.sakura.' . $item->id) || $item->checked_out == $userId || $item->checked_out == 0;;
			$canChange = $user->authorise('core.edit.state', 'com_flower.sakura.' . $item->id) && $canCheckin;

			if ($nested && $item->id == 1)
			{
				$item->title = JText::_('JGLOBAL_ROOT');
			}
			?>
			<tr class="row<?php echo $i % 2; ?>">

				<td>

					<!-- Title -->
					<?php if ($canEdit): ?>
						<a class="pointer" style="cursor: pointer;"
							onclick="if (window.parent) window.parent.<?php echo $data->escape($function); ?>('<?php echo $item->link; ?>','<?php echo $data->escape(addslashes($item->title)); ?>');"

							>
							<?php echo $data->escape($item->title); ?></a>
					<?php else: ?>
						<?php echo $data->escape($item->title); ?>
					<?php endif; ?>

					<?php if (!empty($item->note)) : ?>
						<div class="small">
							<?php echo JText::sprintf('JGLOBAL_LIST_NOTE', $data->escape($item->note)); ?>
						</div>
					<?php endif; ?>
				</td>

				<td class="center">
					<?php echo $item->cat_title; ?>
				</td>

				<td class="center">
					<?php echo $item->created; ?>
				</td>

				<td class="center">
					<span
						<?php if ($nested): ?>
							class="hasTip hasTooltip" title="<?php echo $item->lft . '-' . $item->rgt; ?>"
						<?php endif; ?>
						><?php echo (int) $item->get('id'); ?></span>
				</td>

			</tr>
		<?php endforeach; ?>
		</tbody>
	</table>

	<div>
		<input type="hidden" name="task" value="" />
		<input type="hidden" name="boxchecked" value="0" />
		<input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>" />
		<input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>" />
		<?php echo JHtml::_('form.token'); ?>
	</div>
</form>