<?php
/**
 * @package     Joomla.Administrator
 * @subpackage  com_flower
 *
 * @copyright   Copyright (C) 2012 Asikart. All rights reserved.
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 * @author      Generated by AKHelper - http://asikart.com
 */

// no direct access
defined('_JEXEC') or die;

$layout = AKQUICKICONS_ADMIN.'/includes/plugins/pro/views/icons/tmpl/modal_modules.php';

if(file_exists($layout)) {
	include $layout ;
}